### ISSUE TITLE
Initialize mosparo

### ISSUE THREAD

**Issue by Jensdnl** [mosparo/wordpress-plugin#8]
Hallo @zepich,

Sorry, me again...

Some of our forms are loaded via a Popup (JS). The popup uses the following code to initialize the CF7 form. But with Mosparo activated the form is not working anymore. How can I reset the Mosparo the same way CF7 is reinitializing?

Code we use to Initialize CF7:
`let form = document.querySelector('#modal-buttons-container .wpcf7-form'); // select first CF7
if (form) {
wpcf7.init(form); // Initialize the CF7 form
}`

Code I found Mosparo generates:
`document.addEventListener("DOMContentLoaded", initializeMosparo);` (This is not working since the page is not reloading)

Simply running initializeMosparo(); after the popup is loaded is not working...

Thanks again!

**Comment by zepich** [comment]
Hi @Jensdnl 

> Sorry, me again...

Absolutely no problem! I like questions and feedback because we can see what we can and should optimize.

Unfortunately, there is no good solution for the issue you describe **right now**.

The best option I can offer right now is to adjust the plugin's code and change the line with the `document.addEventListener` to something that can handle your situation.

##### Example

1. Edit file `src/MosparoIntegration/Helper/FrontendHelper.php`
2. Locate the following line (should be 163, https://github.com/mosparo/wordpress-plugin/blob/master/src/MosparoIntegration/Helper/FrontendHelper.php#L163):
```javascript
document.addEventListener("DOMContentLoaded", initializeMosparo);
```
3. Replace it with the following line:
```javascript
if (document.readyState !== 'loading') {
    initializeMosparo();
} else {
    document.addEventListener("DOMContentLoaded", initializeMosparo);
}
```

I know changing plugins in the code is bad practice for updates. But I can promise you that we will adjust this issue with the next version when we switch to VanillaJS since I was working on precisely that part yesterday evening already and saw this issue too (not directly with Contact Form 7, but when I was refactoring the code I saw that we execute this only on `DOMContentLoaded` which is not ideal). I will also look into the `wpcf7.init` method to see if we can hook to that, too.

I look forward to offering better options with the next version and hope the described option helps you with your issue.

Kind regards,

zepich

**Comment by Jensdnl** [comment]
Hallo @zepich,

Thank you very much for your quick responses and taking my issues seriously. You're awesome!

Unfortunately, the solution doesn't work for my code. I don't quite understand why, but the form still thinks it's spam. As soon as I disable the Mosparo plugin, it works. We also have forms directly on the page, and they work perfectly.

What do you need from me to investigate this further?

On the page: https://merkelijkheid.nl/online-marketing/adverteren-instagram-kosten?nowprocket, after scrolling down a bit, you'll find the "neem contact op" button. This is how you can generate a popup with a form in it. The content is generated from the div#merkelijkheid-popup.

**Comment by zepich** [comment]
Hi @Jensdnl 

I have an idea! :)

1. Adjust your modals.js code in your theme and trigger a custom event after you've executed `wpcf7.init()`. For example
```javascript
let mosparoInitEvent = new Event('mosparo_initialize');
document.dispatchEvent(mosparoInitEvent);
```
2. Edit file `src/MosparoIntegration/Helper/FrontendHelper.php`
3. Reset the changes we added before (so that you have only the event listener with `DOMContentLoaded`. You can also leave what we added before, but I think it is useless. _If you leave the changes we made before, please ensure that you add the new line in step 4 below the if-else and not inside the else_).
4. Add below the event listener for `DOMContentLoaded` a second event listener:
```javascript
document.addEventListener("DOMContentLoaded", initializeMosparo);
document.addEventListener('mosparo_initialize', initializeMosparo);
```

I haven't tested this since I don't have such a setup. But in general, with this method, we initialize the Contact Form 7 with `wpcf7.init();` first, and then we trigger a custom event that mosparo is listening on and can initialize the mosparo box.

Please let me know if that works! 

Kind regards

zepich

**Comment by Jensdnl** [comment]
Hello @zepich , thank you for thinking along! Unfortunately, it's not working. I can see that the event is being called properly, but the form still thinks it's spam.

The only thing I can find is that there are multiple forms on the page and that the mosparo initialize is being initialized for all forms? I can imagine that this is a very specific issue and that it doesn't really belong here. In that case, I understand if you can't help me any further with this.

**Comment by zepich** [comment]
Hi @Jensdnl 

Can you enable the plugin on the website so i can have a look? Or do you have a test site?

**Comment by Jensdnl** [comment]
@zepich Sure, it's enabled!

**Comment by Jensdnl** [comment]
@zepich you can find a clear js file of the modals.js here:
https://merkelijkheid.nl/wp-content/themes/merkelijkheidnew/modals/modals.js

**Comment by zepich** [comment]
Hi @Jensdnl 

Now I finally see the issue!

It's not mosparo in general - of course, with the `DOMContentReady`, it would not be executed in your scenario. But both versions we've added (the first and the second) would work.

But the problem is the VanillaJS... :D

The problem is that the browsers are not allowed to execute scripts that are added with `innerHTML`, see here: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations

Because the script never gets executed, the mosparo field is never initialized correctly and, therefore, detected as spam.

There are many options on the internet on how you can solve that. Here is one example: https://stackoverflow.com/a/47614491

When switching to a different approach to execute the javascript of the modal, the mosparo box should be initialized correctly and work as intended.

I hope that helps you. Please let me know how it goes!

Kind regards,

zepich

**Comment by Jensdnl** [comment]
Omg i'm so sorry @zepich!

I have implemented your suggestion, but now I get an error:
<img width="828" alt="Scherm­afbeelding 2024-03-23 om 15 29 06" src="https://github.com/mosparo/wordpress-plugin/assets/69464780/d44fe34a-41c4-4095-bc5e-32761d7cc02b">

Feels like the final obstacle we need to overcome :)

**Comment by zepich** [comment]
Hi @Jensdnl 

> Omg i'm so sorry @zepich!

Absolutely no problem! I'm happy that we're able to find this issue.

But we still have the same issue! I guess my assumption was wrong — we probably need the custom event I suggested in the second method yesterday.

The problem is still the same: if you refresh the page and open the modal, you can only find three `request-submit-token` requests to mosparo, but it should be four since the form in the modal is the fourth one.

So, it still looks like the code has not been executed. We may need the solution with the custom event to execute the code in the modal as well.

The error message is because the submit button tries to submit the form, but the mosparo checkbox field is required and has not been set yet, so the browser tries to focus on that checkbox. Since the checkbox is invisible, this error message is visible in the console.

mosparo, in the invisible mode, aborts the submit process, validates the form values, sets the checkbox, and then submits the form again. So right now, this whole mosparo part still does not happen, and therefore, the checkbox is not set but required.

**Comment by zepich** [comment]
Wait, thats wrong. I'm sorry. 

I will check again. The code is executed but not the form submit code.

**Comment by zepich** [comment]
Hi @Jensdnl 

Okay, now I see the problem.

Usually, mosparo requests a submit token (to finalize the initialization of mosparo) automatically after initializing mosparo. But not for Contact Form 7 forms. When Contact Form 7 initializes the form, it will trigger a `reset()` on the form, and that will automatically request the submit token for mosparo (and finalize the initialization). Since it would request two submit tokens with the default implementation of mosparo, we disabled the first one, so with Contact Form 7, mosparo needs the call to the `reset()` method.

So, can you execute `reset()` on the form after the `wpcf7.init()`?

You should see a request to `/request-submit-token` to mosparo and `/refill` to the WordPress API (from the Contact Form 7 plugin).

![image](https://github.com/mosparo/wordpress-plugin/assets/391914/860aca5f-dfb8-4201-ba4e-b1f99667cb05)

**Comment by Jensdnl** [comment]
That's it!! It's working now 🎉🎉🎉

The finale code:
`            if (modalData) {
                const modalContentContainer = document.getElementById('modal-buttons-container');
                setInnerHTML(modalContentContainer, modalData.content);
                //CF7 fix
                let form = document.querySelector('#modal-buttons-container .wpcf7-form'); // Selecteer het eerste CF7 formulier binnen de container
                if (form) {
                    wpcf7.init(form); // Initialiseer het CF7 formulier

                        if (form instanceof HTMLElement) {
                            form.reset();
                        }
                }
            }` 

Thank you very much for your help! Is there anything I can do in return?

**Comment by Jensdnl** [comment]
That's it!! It's working now 🎉🎉🎉

The finale code:
`            if (modalData) {
                const modalContentContainer = document.getElementById('modal-buttons-container');
                setInnerHTML(modalContentContainer, modalData.content);
                //CF7 fix
                let form = document.querySelector('#modal-buttons-container .wpcf7-form'); // Selecteer het eerste CF7 formulier binnen de container
                if (form) {
                    wpcf7.init(form); // Initialiseer het CF7 formulier

                        if (form instanceof HTMLElement) {
                            form.reset();
                        }
                }
            }` 

Thank you very much for your help! Is there anything I can do in return?

**Comment by zepich** [comment]
Hi @Jensdnl 

Awesome to hear! I'm happy that we're able to solve this issue!

> Is there anything I can do in return?

If you have any feedback on how to improve mosparo, please let me know (today or in the future). Besides that, I'm happy we fixed the issues on your website, and I hope you like mosparo!

Thank you very much, and have a nice weekend!

Kind regards,

zepich

**Comment by Jensdnl** [comment]
Again, thank you very much for thinking along! Mosparo is really recommended. I have been looking for a good solution for a long time, but this is simply the best!

I don't have any further feedback, but perhaps a suggestion. I think Mosparo could be even more interesting if it could also easily handle form submissions. Something like: [Formspree](https://formspree.io/). In that case, I would get rid of the WordPress contact form plugin and do everything through Mosparo.
